[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "binary-waterfall-ng"
version = "0.1.0"
readme = "README.md"
description = "A Cross-Platform Raw Data Media Player"
license= {file = "LICENSE"}
authors = [
    {name = "Aylah Amalthea", email = "aylah.a63@proton.me"},
    {name = "Ella Jameson", email = "ellagjameson@gmail.com"}
]
classifiers = [
    "Topic :: Multimedia",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Multimedia :: Graphics :: Graphics Conversion",
    "Topic :: Multimedia :: Graphics :: Viewers",
    "Topic :: Multimedia :: Sound/Audio",
    "Topic :: Multimedia :: Sound/Audio :: Conversion",
    "Topic :: Multimedia :: Sound/Audio :: Players",
    "Topic :: Multimedia :: Video",
    "Topic :: Multimedia :: Video :: Conversion",
    "Topic :: Multimedia :: Video :: Display"
]
dependencies = [
    "pyyaml",
    "Pillow",
    "PyQt5",
    "pydub",
    "audioop-lts; python_version >= '3.13'",
    "moviepy",
    "proglog"
]

[project.urls]
homepage = "https://github.com/aylah.a63/binary-waterfall-ng"
repository = "https://github.com/aylah.a63/binary-waterfall-ng"
Issues = "https://github.com/aylah.a63/binary-waterfall-ng/issues"

[project.scripts]
binary-waterfall = "binary_waterfall:run"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
